# -*- coding: utf-8 -*-
"""Operators in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZMedcXpJLIGkWDD77F9HEFUxQx7GCbq
"""

# print("-------------Artimetic Operators Begins-----------")
a=int(input("Enter first no. "))
b=int(input("Enter second no."))
c=a+b
print(c)

c=int(input("Enter first no."))
d=int(input("Enter second no. "))
e=c-d
print(e)

c=int(input("Enter first no."))
d=int(input("Enter second no. "))
e=c*d
print(e)

c=int(input("Enter first no."))
d=int(input("Enter second no. "))
e=c/d
print(e)

c=int(input("Enter first no."))
d=int(input("Enter second no. "))
e=c%d
print(e)

c=int(input("Enter first no."))
d=int(input("Enter second no. "))
e=c//d
print(e)

c=int(input("Enter first no."))
d=int(input("Enter second no. "))
e=c**d
print(e)
# print("-------------Artimetic Operators Ends-----------")

# -----------Assignment Operators begins-----------
a=34
print(a)

a=35
a+=56
print(a)

a=35
a-=56
print(a)

a=35
a*=56
print(a)

a=35
a/=56
print(a)

a=35
a//=56
print(a)

a=35
a%=56
print(a)

a=35
a**=56
print(a)
# Assignment Operators Ends

# Logical Operators Begin
a=45
b=23
print(a==b)

a=455
b=564
print(a>b)

a=45
b=46
print(a<b)

a=45
b=45
print(a>=b)

a=56
b=56
print(a<=b)

a=56
b=46
print(a!=b)